package io.github.samolego.ascendo_trainboard.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

private val lightScheme = lightColorScheme(
    primary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.primaryLight,
    onPrimary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onPrimaryLight,
    primaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.primaryContainerLight,
    onPrimaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onPrimaryContainerLight,
    secondary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.secondaryLight,
    onSecondary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSecondaryLight,
    secondaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.secondaryContainerLight,
    onSecondaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSecondaryContainerLight,
    tertiary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.tertiaryLight,
    onTertiary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onTertiaryLight,
    tertiaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.tertiaryContainerLight,
    onTertiaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onTertiaryContainerLight,
    error = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.errorLight,
    onError = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onErrorLight,
    errorContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.errorContainerLight,
    onErrorContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onErrorContainerLight,
    background = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.backgroundLight,
    onBackground = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onBackgroundLight,
    surface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceLight,
    onSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSurfaceLight,
    surfaceVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceVariantLight,
    onSurfaceVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSurfaceVariantLight,
    outline = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.outlineLight,
    outlineVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.outlineVariantLight,
    scrim = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.scrimLight,
    inverseSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inverseSurfaceLight,
    inverseOnSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inverseOnSurfaceLight,
    inversePrimary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inversePrimaryLight,
    surfaceDim = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceDimLight,
    surfaceBright = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceBrightLight,
    surfaceContainerLowest = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceContainerLowestLight,
    surfaceContainerLow = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceContainerLowLight,
    surfaceContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceContainerLight,
    surfaceContainerHigh = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceContainerHighLight,
    surfaceContainerHighest = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
    primary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.primaryDark,
    onPrimary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onPrimaryDark,
    primaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.primaryContainerDark,
    onPrimaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onPrimaryContainerDark,
    secondary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.secondaryDark,
    onSecondary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSecondaryDark,
    secondaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.secondaryContainerDark,
    onSecondaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSecondaryContainerDark,
    tertiary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.tertiaryDark,
    onTertiary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onTertiaryDark,
    tertiaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.tertiaryContainerDark,
    onTertiaryContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onTertiaryContainerDark,
    error = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.errorDark,
    onError = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onErrorDark,
    errorContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.errorContainerDark,
    onErrorContainer = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onErrorContainerDark,
    background = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.backgroundDark,
    onBackground = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onBackgroundDark,
    surface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceDark,
    onSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSurfaceDark,
    surfaceVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceVariantDark,
    onSurfaceVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.onSurfaceVariantDark,
    outline = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.outlineDark,
    outlineVariant = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.outlineVariantDark,
    scrim = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.scrimDark,
    inverseSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inverseSurfaceDark,
    inverseOnSurface = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inverseOnSurfaceDark,
    inversePrimary = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.inversePrimaryDark,
    surfaceDim = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceDimDark,
    surfaceBright = _root_ide_package_.io.github.samolego.ascendo_trainboard.ui.theme.surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
)

@Composable
fun TrainBoardAppTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    content: @Composable() () -> Unit
) {
  val colorScheme = when {
      darkTheme -> darkScheme
      else -> lightScheme
  }

  MaterialTheme(
    colorScheme = colorScheme,
    content = content
  )
}
